version: '3'
services:
  ptp-master:
    build: ./ptp/
    image: ptp
    privileged: true
    tty: true
    stdin_open: true
    entrypoint: "ptp4l -S -i eth0 -m"
    volumes:
      - type: bind
        source: ../scripts/
        target: /scripts/
  ptp-slave1:
    build: ./ptp/
    image: ptp
    privileged: true
    tty: true
    stdin_open: true
    # entrypoint: "ptp4l -S -i eth0 -m -s"
    volumes:
      - type: bind
        source: ../scripts/
        target: /scripts/
  iperf-server:
    build: ./ptp/
    image: ptp
    privileged: true
    tty: true
    stdin_open: true
    entrypoint: "iperf3 -s"
    volumes:
      - type: bind
        source: ../scripts/
        target: /scripts/
